export const STARTING_CASH = 1000;
export const REFERRAL_CASH = 1000;
export const REFERRAL_REPUTATION = 2000;
export const PREMIUM_REFERRAL_CASH = 2000;
export const PREMIUM_REFERRAL_REPUTATION = 5000;

export const BASE_CUSTOMER_LIMIT = 500;

export const BASE_LAB_PLOT_PRICE = 989;
export const LAB_PLOT_PRICE_MULTIPLIER = 4;
export const LAB_CAPACITY_MULTIPLIER = 2;
export const LAB_PRODUCTION_MULTIPLIER = 2;

export const BASE_UPGRADE_TIME_SECONDS = 10;

export const ROBBERY_AMOUNT_PER_DAILY_STRIKE = 1000;
export const ROBBERY_MAX_AMOUNT_PER_DAILY_STRIKE = 10000;

export const PVP_NUMBER_OF_PLAYERS = 1;
export const PVP_BASE_ATTACKS_PER_DAY = 2;
export const PVP_BASE_HEALTH_POINTS = 100;
export const PVP_BASE_PROTECTION = 0;
export const PVP_BASE_DAMAGE = 15;
export const PVP_BASE_ACCURACY = 80;
export const PVP_BASE_EVASION = 5;
export const PVP_BASE_LOOT_POWER = 1;
export const PVP_BASE_CRITICAL_HIT_CHANCE = 2;
