export const STARTING_CASH = 1000;
export const REFERRAL_CASH = 1000;
export const REFERRAL_REPUTATION = 500;
export const PREMIUM_REFERRAL_CASH = 2000;
export const PREMIUM_REFERRAL_REPUTATION = 1000;

export const BASE_CUSTOMER_LIMIT = 500;

export const BASE_LAB_PLOT_PRICE = 989;
export const LAB_PLOT_PRICE_MULTIPLIER = 4;
export const LAB_CAPACITY_MULTIPLIER = 1.2;
export const LAB_PRODUCTION_MULTIPLIER = 1.3;

export const SHIPPING_TIME_MULTIPLIER = 1.1;
export const SHIPPING_CAPACITY_PRICE_MULTIPLIER = 1.1;
export const SHIPPING_TIME_PRICE_MULTIPLIER = 1.2;

export const ROBBERY_AMOUNT_PER_DAILY_STRIKE = 1000;
