export const STARTING_CASH = 1000;
export const REFERRAL_CASH = 100;

export const BASE_CUSTOMER_WANTS = 1;
export const BASE_CUSTOMER_LIMIT = 1000;

export const BASE_LAB_PLOT_PRICE = 989;
export const LAB_PLOT_PRICE_MULTIPLIER = 4;
export const LAB_CAPACITY_MULTIPLIER = 2.5;
export const LAB_PRODUCTION_MULTIPLIER = 3;

export const ROBBERY_AMOUNT_PER_DAILY_STRIKE = 1000;
