# This workflow will do a clean installation of node dependencies, cache/restore them and run tests using LTS version of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: lts/*
        cache: 'npm'
    - run: npm ci
    - run: npm run test
      env:
        NODE_ENV: test
        API_PORT: 3000
        TELEGRAM_BOT_TOKEN: 132:AABBCC
        JWT_SECRET: 123
        MONGO_URL: mongodb://mongo:27017
        MONGO_DB: tgang
